description: A highly-available, production-grade Kubernetes cluster.
series: bionic
services:
  containerd:
    annotations:
    charm: cs:~containers/containerd-80
    resources: {}
  easyrsa:
    annotations:
    charm: cs:~containers/easyrsa-318
    constraints: root-disk=8G
    num_units: 1
    resources:
      easyrsa: 5
  etcd:
    annotations:
    charm: cs:~containers/etcd-521
    constraints: root-disk=8G
    num_units: 3
    options:
      channel: 3.3/stable
    resources:
      core: 0
      etcd: 3
      snapshot: 0
  flannel:
    annotations:
    charm: cs:~containers/flannel-492
    resources:
      flannel-amd64: 625
      flannel-arm64: 622
      flannel-s390x: 609
  kubeapi-load-balancer:
    annotations:
    charm: cs:~containers/kubeapi-load-balancer-730
    constraints: mem=4G root-disk=8G
    expose: true
    num_units: 1
    resources: {}
  kubernetes-master:
    annotations:
    charm: cs:~containers/kubernetes-master-850
    constraints: cores=2 mem=4G root-disk=16G
    num_units: 2
    options:
      channel: 1.18/stable
    resources:
      cdk-addons: 0
      core: 0
      kube-apiserver: 0
      kube-controller-manager: 0
      kube-proxy: 0
      kube-scheduler: 0
      kubectl: 0
  kubernetes-worker:
    annotations:
    charm: cs:~containers/kubernetes-worker-682
    constraints: cores=4 mem=4G root-disk=16G
    expose: true
    num_units: 3
    options:
      channel: 1.18/stable
    resources:
      cni-amd64: 645
      cni-arm64: 636
      cni-s390x: 648
      core: 0
      kube-proxy: 0
      kubectl: 0
      kubelet: 0
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - flannel:etcd
  - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni
- - containerd:containerd
  - kubernetes-worker:container-runtime
- - containerd:containerd
  - kubernetes-master:container-runtime